apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: canary
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: canarylab-data-svc
  endpoints:
  - port: http

